---
title: Grace E. Lee - Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
baseurl: 
url: 
twitter_username: gleeit
markdown: kramdown
permalink: "/:title/"
gems:
- jekyll-paginate
paginate: 10
